# Generated by Django 2.2.2 on 2019-06-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_favoritething'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritething',
            options={},
        ),
    ]
