# Generated by Django 2.2.2 on 2019-06-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190621_2034'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favoritething',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('title', 'category', 'user'), name='unique_favorite_thing'),
        ),
    ]
