# Generated by Django 2.2.2 on 2019-06-24 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190624_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='favorite_thing',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
