# Generated by Django 2.2.2 on 2019-07-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190624_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritething',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
