# Generated by Django 2.2.2 on 2019-06-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190617_0929'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryuser',
            unique_together={('category', 'user')},
        ),
    ]
