# Generated by Django 2.2.2 on 2019-06-20 22:59

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190617_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteThing',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('favorite_thing_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('ranking', models.PositiveIntegerField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_things', to='core.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_things', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_favorite_thing',
                'ordering': ['ranking'],
            },
        ),
    ]
