# Generated by Django 2.2.2 on 2019-06-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190622_2204'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoritething',
            name='unique_favorite_thing',
        ),
        migrations.RemoveField(
            model_name='category',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='favoritething',
            name='deleted',
        ),
        migrations.AddConstraint(
            model_name='favoritething',
            constraint=models.UniqueConstraint(fields=('title', 'category', 'user'), name='unique_favorite_thing'),
        ),
    ]
