# Generated by Django 2.2.2 on 2019-06-24 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190624_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('favorite_thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='core.FavoriteThing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
